# Service configuration
services:
  service1:
    build: ./Service1
    environment:
      - PORT=${SVC1_PORT}
    ports:
      - "${SVC1_PORT}:${SVC1_PORT}"
    networks:
      - internal
    volumes:
      - "${PWD}/vstorage:/vstorage:rw" # Will not work if filepath contains spaces

  service2:
    build: ./Service2
    environment:
      - PORT=${SVC2_PORT}
    networks:
      - internal
    volumes:
      - "${PWD}/vstorage:/vstorage:rw" # Will not work if filepath contains spaces

  storage:
    build: ./Storage
    environment:
      - PORT=${STR_PORT}
    networks:
      - internal
    volumes:
      - storage:/data

# Network configuration
networks:
  internal:

# Persistent storage
volumes:
  storage: