[package]
name = "Service2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["tokio", "http1"] }
chrono = "0.4.42"
sysinfo = "0.37.0"
tokio = { version = "1.47.1", features = ["full"] }
